# Generated by Django 4.0.3 on 2022-09-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='lol',
            field=models.TextField(null=True),
        ),
    ]
