# Generated by Django 4.0.3 on 2022-09-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_producto_lol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fechaCambioContraseña',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
