# Generated by Django 4.0.3 on 2022-09-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_fechacambiocontrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='deletedAt',
            field=models.DateField(null=True),
        ),
    ]
