# Generated by Django 4.0.3 on 2022-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_reserva_idlugar_alter_reserva_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='idProductos',
            field=models.JSONField(null=True),
        ),
    ]
