# Generated by Django 4.0.3 on 2022-09-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usuario_departament_alter_usuario_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departament',
            field=models.TextField(blank=True, null=True),
        ),
    ]
