# Generated by Django 4.0.3 on 2022-09-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_lugar_deletedat_alter_producto_deletedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
