# Generated by Django 4.0.3 on 2022-09-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usuario_departament'),
        ('api', '0010_alter_lugar_createdat_alter_lugar_deletedat_and_more'),
    ]

    operations = [
    ]
