# Generated by Django 4.0.3 on 2022-10-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_usuario_changepasswordcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Por iniciar'), (2, 'En proceso'), (3, 'Finalizado'), (4, 'Cancelado')], default=1),
        ),
    ]
