# Generated by Django 4.0.3 on 2022-10-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_reserva_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidadProducto',
            field=models.IntegerField(null=True),
        ),
    ]
