# Generated by Django 4.0.3 on 2022-10-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_reserva_cantidadproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='oficio',
            field=models.IntegerField(choices=[(1, 'Profesor'), (2, 'Estudiante'), (3, 'Investigador'), (4, 'Otro')], null=True),
        ),
    ]
