# Generated by Django 4.0.3 on 2022-10-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_usuario_fechanacimiento_alter_usuario_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
