# Generated by Django 4.0.3 on 2022-10-12 19:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('nombre', models.TextField()),
                ('apellidoPaterno', models.TextField()),
                ('apellidoMaterno', models.TextField()),
                ('genero', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], null=True)),
                ('fechaNacimiento', models.DateField(null=True)),
                ('oficio', models.IntegerField(choices=[(1, 'Profesor'), (2, 'Estudiante'), (3, 'Investigador'), (4, 'Otro')], null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('changePasswordCode', models.TextField(null=True)),
                ('rol', models.IntegerField(blank=True, choices=[(1, 'Admin general'), (2, 'Admin parcial')], null=True)),
                ('fechaBloqueo', models.DateTimeField(blank=True, null=True)),
                ('fechaDesbloqueo', models.DateTimeField(blank=True, null=True)),
                ('fechaCambioContraseña', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('departament', models.TextField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('piso', models.TextField()),
                ('capacidad', models.IntegerField()),
                ('detalles', models.TextField(blank=True)),
                ('salon', models.TextField()),
                ('fechaBloqueo', models.DateTimeField(blank=True, null=True)),
                ('fechaDesbloqueo', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Lugar',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('detalles', models.TextField(blank=True)),
                ('modelo', models.TextField()),
                ('noSerie', models.IntegerField()),
                ('categoria', models.IntegerField(choices=[(1, 'Routers'), (2, 'Switches'), (3, 'Computadoras'), (4, 'Cisco Software'), (5, 'Software de Cálculo'), (6, 'Cableado'), (7, 'Antivirus')])),
                ('cantidadTotal', models.IntegerField()),
                ('cantidadSolicitada', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(choices=[(1, 'SOFTWARE'), (2, 'HARDWARE')])),
                ('fechaBloqueo', models.DateTimeField(blank=True, null=True)),
                ('fechaDesbloqueo', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigoReserva', models.TextField(unique=True)),
                ('cantidadProducto', models.IntegerField(null=True)),
                ('fechaInicio', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('startDate', models.DateTimeField(null=True)),
                ('endDate', models.DateTimeField(null=True)),
                ('horaInicio', models.TextField(null=True)),
                ('horaFinal', models.TextField(null=True)),
                ('estatus', models.IntegerField(choices=[(1, 'Por iniciar'), (2, 'En proceso'), (3, 'Finalizado'), (4, 'Cancelado')], default=1)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('idLugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.lugar')),
                ('idProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.producto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reserva',
            },
        ),
        migrations.AddField(
            model_name='lugar',
            name='idProductos',
            field=models.ManyToManyField(to='api.producto'),
        ),
    ]
