# Generated by Django 4.1.2 on 2022-10-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_fechacambiocontraseña_usuario_fechacambiocontrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cantidadProducto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='changePasswordCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
