# Generated by Django 4.1.2 on 2022-10-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lugar_deletedat_alter_producto_deletedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='idProductos',
            field=models.ManyToManyField(blank=True, to='api.producto'),
        ),
    ]
