# Generated by Django 4.1.2 on 2022-10-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lugar_idproductos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='idLugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.lugar'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.producto'),
        ),
    ]
