# Generated by Django 4.0.3 on 2022-09-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_lugar_idproductos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='deletedAt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='deletedAt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='deletedAt',
            field=models.DateField(null=True),
        ),
    ]
