# Generated by Django 4.0.3 on 2022-09-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_reserva_horafinal_reserva_horainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fechaFinal',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
