# Generated by Django 4.0.3 on 2022-09-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto_lol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='lol',
        ),
    ]
