# Generated by Django 4.0.3 on 2022-09-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_reserva_fechafinal_alter_reserva_fechainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='changePasswordCode',
            field=models.TextField(null=True),
        ),
    ]
